### ISSUE TITLE
Termial color change doesn't work with Mingw / Windows Terminal

### ISSUE THREAD

**Issue by HiFiPhile** [hirdrac/makefile#2]
Thanks for this awesome project !

I met a minor issue is that color change doesn't work with Mingw or Windows Terminal, instead these control sequence mess up with compile output makes them hard to read.

![image](https://github.com/hirdrac/makefile/assets/4375114/2dae494c-4eb6-49ba-aeb2-bf72e733e398)
![image](https://github.com/hirdrac/makefile/assets/4375114/e7896863-61af-46ea-b330-21b0b904151f)

**Comment by hirdrac** [comment]
Strange the ANSI color codes aren't supported - I added this fallback for my MSys2 terminal and I believe it also worked for Cygwin.
Another option I've looked into was for using the 'tput' command (part of the ncurses package).  If this is available in your environment, I can try using it instead of 'setterm'.

**Comment by HiFiPhile** [comment]
Sorry I just tested on another PC and it's a Mingw issue.

Old GNU Make 4.3 under Mingw64 was leftover and was used instead, once it's removed updated Make output color correctly.
